version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: django-app
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      sh -c "python manage.py migrate &&
             daphne -b 0.0.0.0 -p 8000 backend.asgi:application"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: vue-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
