# Generated by Django 6.0.4 on 2026-04-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_is_read_alter_message_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='fraud_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_fraud',
            field=models.BooleanField(default=False),
        ),
    ]
