# Generated by Django 4.2.30 on 2026-05-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_audio_message_message_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='transcript',
            field=models.TextField(blank=True, default=''),
        ),
    ]
