# Generated by Django 5.2.1 on 2025-05-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birth_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='display_name',
            field=models.CharField(default='Новый пользователь', max_length=50),
        ),
    ]
