# Generated by Django 5.2.1 on 2025-05-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_birth_year_customuser_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='birth_year',
        ),
        migrations.AddField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='display_name',
            field=models.CharField(default='Пользователь', max_length=50),
        ),
    ]
